-- AlterTable
ALTER TABLE "DraftPick" ALTER COLUMN "playerRating" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "goalieRating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Player" ALTER COLUMN "playerRating" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "goalieRating" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lockerRating" SET DATA TYPE DOUBLE PRECISION;
